name: "cat-website"
navbar:
  title: "My cats' website"
left:
  - text: "Home"
href: index.html
right: 
  - icon: fa-envelope fa-lg
href: mailto:<cats@catemail.com>
  - icon: fa-github fa-lg
href: http://github.com/DrFloReiche/
  output:
  html_document:
  remote_theme: tuur29/pages-themes-cayman